datatype = "xPData"

[test_container]
[[test_container.data]]
datatype = "xPData"

[test_container.data.some_numpy.data]
extra_fname = "test_c/extra/data_1_numpy.npy"
type = "<class 'numpy.ndarray'>"
[test_container.data.some_numpy.header]
name = "some_numpy"
[[test_container.data]]
datatype = "xPData"

[test_container.data.some_text]
data = "test"
[test_container.data.some_text.header]
name = "some_text"

[test_container.header]
name = "test_container"

[test_container.meta]
