import mne
import re
from mne import create_info
from mne.io.constants import FIFF

from datetime import datetime


def read_epochs_fif(fname, info=None):
    f = mne.read_epochs(fname)
    try:
        ch_types = [re.findall('_([^_]*)_CH$', c['kind']._name)[0].lower()
                    for c in f.info['chs']]

    # TODO: check of the specific Exception and only escape this
    except Exception as e:
        print(f"Encountered exception {e} -- continue with legacy mode")
        ch_types = 'eeg'                # hack for legacy

    if info is None:
        # if none simply use from file
        info = create_info(f.info['ch_names'],
                           sfreq=f.info['sfreq'],
                           ch_types=ch_types
                           )
    else:
        info_obj = create_info(info.pop('ch_names'),
                               sfreq=info.pop('sfreq'),
                               ch_types=ch_types
                               )
        for k, v in info.items():
            info_obj[k] = v
        info = info_obj

    # change things that have been generated by the reading process
    for i, ch in enumerate(info['chs']):
        # unit_mul is named int after being read
        info['chs'][i]['unit_mul'] = int(ch['unit_mul'])

        # coord_frame has switched types
        # TODO: this one is not dynamic!!
        info['chs'][i]['coord_frame'] = FIFF.FIFFV_COORD_UNKNOWN

    # custom_ref_applied uses namedint instead of bool
    info['custom_ref_applied'] = bool(info['custom_ref_applied'])
    f.info = info

    return f


def read_raw_fif(fname, info=None):
    """ Just load via mne --> consider changes necessary for epochs
    TODO: double check if necessary

    info - only for compatebility
    """

    return mne.io.read_raw(fname)


def read_ica_fif(fname, info=None):
    """ Just load via mne --> consider changes necessary for epochs
    TODO: double check if necessary

    info - only for compatebility
    """

    return mne.preprocessing.read_ica(fname)


def _construct_info_from_dict(ch_names, sfreq, chs, custom_ref_applied,
                              file_id, meas_id, meas_date, highpass, lowpass,
                              dig, ch_types='eeg', **kwargs):
    # this exists because the create_info function doesn't allow you to specify
    # a lot of the stuff
    # --> only casting to ch_types='eeg' will be a problem
    # --> derive the ch type from the 'chs' names
    try:
        ch_types = [re.findall('_([^_]*)_CH$', c['kind']._name)[0].lower()
                    for c in chs]

    # TODO: check of the specific Exception and only escape this
    except Exception as e:
        print(f"Encountered exception {e} -- continue with legacy mode")
        ch_types = 'eeg'                # hack for legacy

    info = create_info(ch_names, sfreq=sfreq, ch_types=ch_types)
    info['file_id'] = file_id
    info['meas_id'] = meas_id
    if isinstance(meas_date, tuple) or meas_date is None:
        info['meas_date'] = meas_date
    else:
        info['meas_date'] = datetime.strptime(meas_date, '%Y%m%d%H%M%S')

    info['highpass'] = highpass
    info['lowpass'] = lowpass
    info['dig'] = dig
    # change things that have been generated by the reading process

    for i, ch in enumerate(info['chs']):
        # unit_mul is named int after being read
        info['chs'][i]['unit_mul'] = int(ch['unit_mul'])

        # set scanno and logno
        info['chs'][i]['scanno'] = chs[i]['scanno']
        info['chs'][i]['logno'] = chs[i]['logno']
        info['chs'][i]['cal'] = chs[i]['cal']
        info['chs'][i]['loc'] = chs[i]['loc']

    # custom_ref_applied uses namedint instead of bool
    info['custom_ref_applied'] = bool(info['custom_ref_applied'])

    return info
