# xData { #xileh.core.pipelinedata.xData }

```python
core.pipelinedata.xData(
    data,
    header: dict | None = None,
    meta: dict | None = None,
    name: str | None = None,
)
```

The generalized pipeline data container

## Methods

| Name | Description |
| --- | --- |
| [add](#xileh.core.pipelinedata.xData.add) | Convenience alias creating a new container |
| [copy](#xileh.core.pipelinedata.xData.copy) | Create a copy of the container and return it. This method is |
| [delete_by_name](#xileh.core.pipelinedata.xData.delete_by_name) | Look for a subcontainer with the given name and drop it |
| [gc](#xileh.core.pipelinedata.xData.gc) | Convenience alias for get_containers |
| [get_by_name](#xileh.core.pipelinedata.xData.get_by_name) | Traverse the data container and look for a (sub) container |
| [get_container_names](#xileh.core.pipelinedata.xData.get_container_names) | Get all container names |
| [get_containers](#xileh.core.pipelinedata.xData.get_containers) | Return a dict of data entity names and types |
| [overwrite](#xileh.core.pipelinedata.xData.overwrite) | Overwrite data, header and meta of this container by |
| [rename](#xileh.core.pipelinedata.xData.rename) | Changes a containers name |
| [save](#xileh.core.pipelinedata.xData.save) | Store the container to a given folder name |

### add { #xileh.core.pipelinedata.xData.add }

```python
core.pipelinedata.xData.add(
    value,
    name: str = '',
    header: dict | None = None,
    meta: dict | None = None,
)
```

Convenience alias creating a new container

### copy { #xileh.core.pipelinedata.xData.copy }

```python
core.pipelinedata.xData.copy()
```

Create a copy of the container and return it. This method is
convenience and helps to avoid issues which deepcopy encounters for
copying nested structures

### delete_by_name { #xileh.core.pipelinedata.xData.delete_by_name }

```python
core.pipelinedata.xData.delete_by_name(name)
```

Look for a subcontainer with the given name and drop it

### gc { #xileh.core.pipelinedata.xData.gc }

```python
core.pipelinedata.xData.gc()
```

Convenience alias for get_containers

### get_by_name { #xileh.core.pipelinedata.xData.get_by_name }

```python
core.pipelinedata.xData.get_by_name(
    name,
    create_if_missing,
    find_parent,
    parent,
)
```

Traverse the data container and look for a (sub) container
with the given name and return it if found

#### Parameters {.doc-section .doc-section-parameters}

| Name              | Type        | Description                                                                                                                  | Default    |
|-------------------|-------------|------------------------------------------------------------------------------------------------------------------------------|------------|
| name              | str         | name to look up in the data containers header dict                                                                           | _required_ |
| create_if_missing | bool        | if no container is found, create a new one with the given name and append to the self.data if it is a list, else raise Error | `False`    |
| find_parent       | bool        | if true return the parent container instead                                                                                  | `False`    |
| parent            | xileh.xData | a container to store the parent to be returned if find_parent is true. Used for recursive call of the method.                | `None`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                 | Description                                                                                   |
|--------|----------------------|-----------------------------------------------------------------------------------------------|
|        | data : xData or None | A data container with the given name or None if no container with the given name can be found |

### get_container_names { #xileh.core.pipelinedata.xData.get_container_names }

```python
core.pipelinedata.xData.get_container_names()
```

Get all container names

### get_containers { #xileh.core.pipelinedata.xData.get_containers }

```python
core.pipelinedata.xData.get_containers()
```

Return a dict of data entity names and types

### overwrite { #xileh.core.pipelinedata.xData.overwrite }

```python
core.pipelinedata.xData.overwrite(new_pdata)
```

Overwrite data, header and meta of this container by
referencing to a "new_data" container

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type   | Description                                          | Default    |
|-----------|--------|------------------------------------------------------|------------|
| new_pdata | xData  | a new container to overwrite this containers content | _required_ |

### rename { #xileh.core.pipelinedata.xData.rename }

```python
core.pipelinedata.xData.rename(from_name, to_name)
```

Changes a containers name

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type   | Description                     | Default    |
|-----------|--------|---------------------------------|------------|
| from_name | str    | name of the container to rename | _required_ |
| to_name   | str    | new name of the container       | _required_ |

### save { #xileh.core.pipelinedata.xData.save }

```python
core.pipelinedata.xData.save(fname)
```

Store the container to a given folder name

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                | Description                               | Default    |
|--------|---------------------|-------------------------------------------|------------|
| fname  | str or pathlib.Path | folder path and name to store the data to | _required_ |